# REFERENCES:  https://stackoverflow.com/questions/42267299/ansible-install-mysql-5-7-set-root-user-password?rq=1
- name: Copy db.properties File
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/db.properties.template"
    dest: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/db.properties"
    remote_src: yes

- name: Copy hibernate.properties File
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/resources/hibernate.properties.template"
    dest: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/resources/hibernate.properties"
    remote_src: yes

- name: Copy email.properties File
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/email.properties.template"
    dest: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/email.properties"
    remote_src: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/db.properties"
    state: present
    regexp: 'user'
    line: "user {{ env_vars.mysql_user }}"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/db.properties"
    state: present
    regexp: 'password'
    line: "password {{ env_vars.mysql_password }}"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/db.properties"
    state: present
    regexp: 'localhost'
    line: "url jdbc:mysql://{{ env_vars.mysql_host }}:3306/iTrust2?createDatabaseIfNotExist=true"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/email.properties"
    state: present
    regexp: 'username'
    line: "username {{ env_vars.MAIL_USER }}"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/java/email.properties"
    state: present
    regexp: 'password'
    line: "password {{ env_vars.MAIL_PASSWORD }}"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/resources/hibernate.properties"
    state: present
    regexp: 'hibernate.connection.password'
    line: "hibernate.connection.password = {{ env_vars.mysql_password }}"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/resources/hibernate.properties"
    state: present
    regexp: 'hibernate.connection.url'
    line: "hibernate.connection.url = jdbc:mysql://{{ env_vars.mysql_host }}:3306/iTrust2?createDatabaseIfNotExist=true"
    backrefs: yes

- lineinfile:
    path: "{{ ansible_env.HOME }}/itrust/iTrust2/src/main/resources/hibernate.properties"
    state: present
    regexp: 'hibernate.connection.username'
    line: "hibernate.connection.username = {{ env_vars.mysql_user }}"
    backrefs: yes

- name: Populate data
  shell: mvn process-test-classes
  args:
    chdir: "{{ ansible_env.HOME }}/itrust/iTrust2"

- name: Run Server
  shell: nohup mvn jetty:run &
  args:
    chdir: "{{ ansible_env.HOME }}/itrust/iTrust2"
