# https://medium.com/@tedchength/installing-docker-using-ansible-script-c182787f2fa1
- name: Add Docker apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    update_cache: yes

- name: Install Docker-ce
  become: yes
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Ensure group "docker" exists
  become: yes
  group:
    name: docker
    state: present

- name: Add the user 'vagrant' and 'ubuntu' to docker
  become: yes
  user:
    name: "{{ item }}"
    group: docker
  with_items:
    - vagrant
    - ubuntu

- name: Install docker compose
  become: yes
  apt:
    name: docker-compose