---
# REFERENCES: https://stackoverflow.com/questions/37568848/how-to-install-mongodb-with-ansible
- name: Add Mongodb ppa key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present

- name: Add mongodb sources list
  become: yes
  lineinfile:
    line: "deb http://repo.mongodb.com/apt/ubuntu xenial/mongodb-enterprise/3.6 multiverse"
    dest: /etc/apt/sources.list.d/mongodb-enterprise.list
    state: present
    create: yes

- name: Install mongo
  become: yes
  apt:
    name: mongodb-enterprise
    state: latest
    update_cache: yes

- name: Start mongod service
  become: yes
  service:
    name: mongod
    state: started

#### Configure Mongodb ####
- name: Install python-pip
  become: yes
  apt:
    name: python-pip
    state: present

- name: Install pyMongo
  become: yes
  pip:
    name: pyMongo
    state: present

- name: Add user to mongodb
  vars:
    - mongo_user:  "{{ env_vars.MONGO_USER }}"
    - mongo_password: "{{ env_vars.MONGO_PASSWORD }}"
  mongodb_user:
    database: admin
    name: "{{mongo_user}}"
    password: "{{mongo_password}}"
    state: present
    roles: dbAdmin,userAdminAnyDatabase,readWriteAnyDatabase
