- name: Install python-pip, awscli
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python-pip
    - awscli

- name: Install boto for ec2 Ansible module
  become: yes
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - boto
    - boto3
