---
- name: Deploy Checkbox Server ec2 Instance
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Create an AWS server for Checkbox
    ec2:
      key_name: Devops
      instance_type: t2.micro
      image: ami-965e6bf3
      wait: yes
      count: 1
      region: us-east-2
      state: present
    register: aws
  - debug: 
      msg: Created instance "{{ aws.instances[0].id }}" and ip "{{ aws.instances[0].public_ip }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ aws.instances }}"

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: checkbox.io
    with_items: "{{ aws.instances }}"

  # Some instances might not come with python installed, so we're gonna download it
  - name: Force install python
    shell: ssh -o "StrictHostKeyChecking no" -i /home/ubuntu/.ssh/Devops.pem ubuntu@{{ aws.instances[0].public_ip }} "sudo apt-get -y install python"

- name: "Configure Checkbox Server and Run"
  hosts: checkbox.io
  gather_facts: yes
  vars:
    - ansible_user: 'ubuntu'
    - ansible_ssh_private_key_file: 'home/ubuntu/.ssh/Devops.pem'
  roles: 
    - checkbox.io