---
- hosts: local
  gather_facts: no
  tasks:
  - name: Install python 2
    raw: sudo test -e /usr/bin/python || (sudo apt-get install -y python-minimal)

- hosts: local
  gather_facts: yes
  ignore_errors: yes
  roles:
  #  - configure-checkbox
  # - configure-itrust
    - configure-jenkins
