---
- name: Restart Jenkins again to ready plugins
  become: yes
  service:
    name: jenkins
    state: restarted

# Make sure Jenkins is ready to run after last restart
- name: Ensure Jenkins is up and running
  uri:
    url: "http://localhost:{{env_vars.jenkins_port | int }}"
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200