- name: Install git
  become: yes
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Clone checkbox.io
  git:
    repo: https://github.com/chrisparnin/checkbox.io.git
    dest: "{{ ansible_env.HOME }}/checkbox/"
    force: yes

- name: Build checkbox.io
  npm:
    path: "{{ ansible_env.HOME }}/checkbox/server-side/site/"

- lineinfile:
    path: "{{ ansible_env.HOME }}/checkbox/local-conf/default"
    state: present
    regexp: 'root /Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html/'
    line: '\troot {{ ansible_env.HOME }}/checkbox/public_html/;'
    backrefs: yes

- name: Copy default File
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/checkbox/local-conf/default"
    dest: /etc/nginx/sites-available/default
    remote_src: yes

- name: Copy nginx Config File
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/checkbox/local-conf/nginx.conf"
    dest: /etc/nginx/nginx.conf
    remote_src: yes

- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: Run checkbox.io
  shell: nohup node server.js &
  args:
    chdir: "{{ ansible_env.HOME }}/checkbox/server-side/site/"
