---
- name: Add Mongodb ppa key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present
- name: Add mongodb sources list
  become: yes
  lineinfile: 
    line: "deb http://repo.mongodb.com/apt/ubuntu xenial/mongodb-enterprise/3.6 multiverse"
    dest: /etc/apt/sources.list.d/mongodb-enterprise.list
    state: present
    create: yes
- name: Install mongo
  become: yes
  apt: 
    name: mongodb-enterprise
    state: latest
    update_cache: yes