- name: Install pip, mysqlclient
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python-pip
    - libmysqlclient-dev
# REFERENCE: https://stackoverflow.com/questions/25865270/how-to-install-python-mysqldb-module-using-pip

- name: Install mysql-python
  become: yes
  pip:
    name: MySQL-python
    state: latest
