---
- hosts: local
  gather_facts: yes
  environment:
    AWS_ACCESS_KEY_ID: "{{ env_vars.ACCESS_KEY }}"
    AWS_SECRET_ACCESS_KEY: "{{ env_vars.SECRET_KEY }}"
  roles:
    - provision-config
    - provision-mysql
    - provision-itrust

- hosts: all
  gather_facts: no
  tasks:
  - name: Install python 2
    raw: sudo test -e /usr/bin/python || (sudo apt-get install -y python-minimal)

- hosts: mysql
  gather_facts: yes
  roles:
    - configure-mysql

- hosts: itrust
  gather_facts: yes
  roles:
    - configure-itrust
    - deploy-itrust

- hosts: local
  gather_facts: yes
  roles:
    - monitoring
