---
- name: Add official APT repository
  become: yes
  apt_repository:
    repo: ppa:ansible/ansible
- name: Install Ansible
  become: yes
  apt:
    name: ansible
    state: present
    update_cache: yes