# REFERENCES: https://coderwall.com/p/4ogyuw/ansible-install-java-8
# Java Installation
- name: add repo for java
  apt_repository: repo=ppa:webupd8team/java state=present
  become: yes

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become: yes

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  become: yes

# Update cache
- name: Update APT package cache
  apt: update_cache=yes
  become: yes
  register: updated
# Install Packages
- name: Install Java8, Git, Maven
  apt: name={{ item }} state=latest update-cache=yes force=yes
  with_items:
    - oracle-java8-installer
    - git
    - maven
  when: updated.changed
  become: yes
