- name: Download mysql repo
  get_url:
    url: https://dev.mysql.com/get/mysql-apt-config_0.8.9-1_all.deb
    dest: "{{ ansible_env.HOME }}"
    mode: 0440
  become: yes

- name: Install mysql repo
  apt: "deb={{ ansible_env.HOME }}/mysql-apt-config_0.8.9-1_all.deb"
  become: yes

- name: Install python-mysqldb
  apt:
    name: python-mysqldb
    state: present
    update_cache: yes
  become: yes

- name: check latest version of mysql 5.7
  command: bash -c "apt-cache showpkg mysql-server|grep 5.7|head -1|cut -d' ' -f1"
  register: latestmysql57

- name: Install mysql 57
  apt:
    name: mysql-server={{ latestmysql57.stdout }}
    state: present
    update_cache: yes
  become: yes
