---
- name: Install Jenkins Job Builder
  pip:
    name: jenkins-job-builder

- name: Copy jenkins_files directory
  become: yes
  copy:
    src: ./jenkins_files
    dest: /home/ubuntu/

- name: Run cat to get Initial Jenkins admin pass output
  become: yes
  shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  register: jenkins_admin_password_output

- name: Set Jenkins admin pass from stdout
  set_fact:
    jenkins_admin_password: "{{ jenkins_admin_password_output.stdout }}"

- name: Set Jenkins admin password for jbb ini file
  become: yes
  lineinfile:
    path: /home/ubuntu/jenkins_files/jbb_config.ini
    regexp: "^password="
    line: "password={{ jenkins_admin_password }}"
  
- name: Upload Jobs to Jenkins
  shell: 'jenkins-jobs --conf jbb_config.ini update sample_job.yml'
  args:
    chdir: /home/ubuntu/jenkins_files
  tags:
    upload