- name: Install boto
  become: yes
  pip:
    name: boto3
    state: present

- name: Create an AWS server for Jenkins
  ec2:
    key_name: Devops
    instance_type: t2.micro
    image: ami-965e6bf3
    wait: yes
    count: 1
    region: us-east-2
    state: present
  register: aws
- debug: 
    var: aws.instances[0].id

- name: Get public key of EC2 instance
  # vars:
  #   - aws: "i-0c87635138dd81fa5"
  shell: aws ec2 get-console-output \
          --region us-east-2 \
          --instance-id "{{aws.instances[0].id}}" \
          --output text|sed -n 's/^.*\(ecdsa-sha2-nistp256 \)\(.*\)/\2/p' | awk '{print $1}'
  register: key_results
  retries: 100
  until: key_results.stdout != ''

- name: Register public key to known_hosts
  lineinfile: 
    name: /home/vagrant/.ssh/known_hosts 
    create: yes
    line: "{{ aws.instances[0].public_ip }} ecdsa-sha2-nistp256 {{key_results.stdout}}"
    insertafter: EOF
    state: present

- name: Update inventory
  lineinfile:
    path: /server/inventory
    insertafter: [ec2]
    line: "{{aws.instances[0].public_ip}}" ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/keys/Devops.pem"
    state: present