- name: Install docker-compose
  become: yes
  get_url: 
    url: https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u=rx,o=rx,g=rx"

- name: Copy checkbox files
  become: yes
  synchronize:
    src: $HOME/CSC519-Project/Infrastructure
    dest: /usr/src/
    recursive: yes

- name: Create docker-compose.yml
  template: 
    src: ./docker-compose.yml
    dest: /usr/src/Infrastructure/docker-compose.yml

- name: Create checkbox docker image
  command: docker-compose up -d
  args:
    chdir: /usr/src/Infrastructure 

- name: Deploy checkbox image
  shell: sudo kubectl run checkbox --image=ankursaxena135/checkbox

- name: Test pod network
  shell: sudo kubectl get nodes
  register: nodes_output

- debug:
    msg: "{{nodes_output.stdout}}"

- name: Test pod network
  shell: sudo kubectl get pods
  register: pods_output

- debug:
    msg: "{{pods_output.stdout}}"