- name: Install python-pip
  become: yes
  apt:
    name: python-pip
    state: latest

- name: Install boto for ec2 Ansible module
  become: yes
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - boto
    - boto3

# REFERENCES: https://wiki.jenkins.io/display/JENKINS/Jenkins+CLI

- name: Install awscli
  become: yes
  apt:
    name: awscli
    state: present
    update_cache: yes

