---
- name: Install python-pip
  become: yes
  apt:
    name: python-pip
    state: latest

- name: Install Jenkins Job Builder
  pip:
    name: jenkins-job-builder

- name: Disable Jenkins' initial authorization wizard
  become: yes
  replace:
    path: /etc/default/jenkins
    regexp: -Djava.awt.headless=true
    replace: -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false

- name: Copy init.grovy to $Jenkins_home
  become: yes
  copy:
    src: ./jenkins_files/init.groovy
    dest: /var/lib/jenkins/init.groovy

- name: Restart Jenkins
  become: yes
  service:
    name: jenkins
    state: restarted

# Try waitng after Jenkins restart
# Sometimes plugin install fails (the next task) if Jenkins not up in time
- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install plugins for Jenkins
  jenkins_plugin:
    name: "{{item}}"
  with_items:
    - git
    - post-build-task

- name: Copy jenkins_files directory
  become: yes
  copy:
    src: ./jenkins_files
    dest: "{{ ansible_env.HOME }}"

- name: Upload Itrust Job to Jenkins
  shell: 'jenkins-jobs update itrust.yml'
  args:
    chdir: "{{ ansible_env.HOME }}/jenkins_files"
  tags:
    upload

- name: Upload Checkbox Job to Jenkins
  shell: 'jenkins-jobs update checkbox.yml'
  args:
    chdir: "{{ ansible_env.HOME }}/jenkins_files"
  tags:
    upload

- name: Trigger build for Checkbox
  become: yes
  shell: "java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/ build 'checkbox-build'"
  tags:
    build-jobs

- name: Trigger build for iTrust
  become: yes
  shell: "java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/ build 'itrust-build'"
  tags:
    build-jobs